# Use a lightweight base image
FROM alpine:latest

# Install necessary packages
RUN apk add --no-cache nfs-utils

# Create shared and mounted directories
RUN mkdir -p /projects /projects/dags /external_projects

# Grant necessary permissions
RUN chmod 777 /projects /projects/dags /external_projects

# Configure NFS exports
RUN echo "/projects *(rw,sync,no_subtree_check,no_root_squash,insecure)" > /etc/exports && \
    echo "/projects/dags *(rw,sync,no_subtree_check,no_root_squash,insecure)" >> /etc/exports && \
    echo "/external_projects *(rw,sync,no_subtree_check,no_root_squash,insecure,fsid=999)" >> /etc/exports

# Copy the NFS startup script
COPY scripts/nfs/start.sh /start-nfs.sh
COPY scripts/nfs/healthcheck.sh /healthcheck.sh
RUN chmod +x /start-nfs.sh /healthcheck.sh

# Expose the NFS port
EXPOSE 2049

# Command to start NFS
CMD ["/start-nfs.sh"]