# Use a lightweight base image
FROM alpine:latest

# Install necessary packages
RUN apk add --no-cache nfs-utils

# Copy the NFS startup script
COPY scripts/nfs/start.sh /start-nfs.sh
COPY scripts/nfs/healthcheck.sh /healthcheck.sh
RUN chmod +x /start-nfs.sh /healthcheck.sh

# Expose the NFS port
EXPOSE 2049

# Command to start NFS
CMD ["/start-nfs.sh"]